[package]
name = "init-pro-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
init-pro-core = { workspace = true }
init-pro-infra = { workspace = true }
init-pro-api = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sha2.workspace = true
zstd.workspace = true
