//! Per-file zstd embed codegen (T0.2 B2, Q6).
//!
//! `generate()` walks `vendor/bin/`, zstd-compresses each file independently,
//! writes content-addressed blobs (`<sha256>.zst`) into `OUT_DIR/assets/`, and
//! emits `OUT_DIR/assets.rs` — a `pub fn embedded_assets() -> &'static
//! [EmbeddedAsset]` built from `include_bytes!` (Rust `//go:embed` equivalent).
//!
//! `generate_empty()` writes an empty registry so the default build (no
//! `INIT_PRO_EMBED`) compiles with zero embedded bytes — `cargo test` stays
//! fast and network-free.

#![forbid(unsafe_code)]

use std::fs;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::dataverify;
use crate::digest;

/// Summary of an embed codegen run.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EmbedReport {
    pub count: usize,
    pub total_bytes: u64,
    pub compressed_bytes: u64,
    /// Source file paths (for `cargo:rerun-if-changed` emission).
    pub files: Vec<PathBuf>,
}

impl EmbedReport {
    pub fn summary(&self) -> String {
        let ratio = self
            .compressed_bytes
            .saturating_mul(100)
            .checked_div(self.total_bytes)
            .unwrap_or(0);
        format!(
            "{} files: {} -> {} bytes ({}%)",
            self.count, self.total_bytes, self.compressed_bytes, ratio
        )
    }
}

/// One entry ready for rendering (internal, separated from I/O for testing).
#[derive(Debug, Clone, PartialEq, Eq)]
struct Entry {
    logical: String,
    sha256: String,
    size: u64,
    compressed_len: u64,
}

/// Walk `vendor/bin/`, compress each file, write blobs + `assets.rs`.
///
/// `vendor_bin` is `vendor/bin/`; logical paths are prefixed with `"bin/"`.
/// `out_dir` is the crate `OUT_DIR` (set by cargo). `level` is the zstd
/// compression level (Q6 target: 19).
pub fn generate(
    vendor_bin: &Path,
    out_dir: &Path,
    level: i32,
) -> Result<EmbedReport, EmbedError> {
    let assets_dir = out_dir.join("assets");
    fs::create_dir_all(&assets_dir).map_err(|e| EmbedError::io("assets dir", e))?;

    let mut files: Vec<PathBuf> = Vec::new();
    walk(vendor_bin, &mut files);
    files.sort();

    if files.is_empty() {
        return Err(EmbedError::no_vendor_bin(vendor_bin.to_path_buf()));
    }

    let mut entries = Vec::with_capacity(files.len());
    let mut total = 0u64;
    let mut compressed = 0u64;
    let mut written_blobs = std::collections::HashSet::new();

    for abs in &files {
        let rel = abs.strip_prefix(vendor_bin).unwrap_or_else(|_| abs);
        let logical = format!("bin/{}", rel.to_string_lossy().replace('\\', "/"));

        let data = fs::read(abs).map_err(|e| EmbedError::io("read source", e))?;
        let sha = digest::sha256_reader(std::io::Cursor::new(&data))
            .map_err(|e| EmbedError::io("hash source", e))?;
        let zdata = zstd_compress(&data, level)?;

        // Content-addressed blob: identical files share one blob (dedup, Q6).
        if written_blobs.insert(sha.clone()) {
            let blob_path = assets_dir.join(format!("{sha}.zst"));
            fs::write(&blob_path, &zdata).map_err(|e| EmbedError::io("write blob", e))?;
        }

        total += data.len() as u64;
        compressed += zdata.len() as u64;
        entries.push(Entry {
            logical,
            sha256: sha,
            size: data.len() as u64,
            compressed_len: zdata.len() as u64,
        });
    }

    entries.sort_by(|a, b| a.logical.cmp(&b.logical));
    let src = render(&entries, &assets_dir);
    fs::write(out_dir.join("assets.rs"), src).map_err(|e| EmbedError::io("write assets.rs", e))?;

    Ok(EmbedReport {
        count: entries.len(),
        total_bytes: total,
        compressed_bytes: compressed,
        files,
    })
}

/// Write an empty `assets.rs` (default build: no `INIT_PRO_EMBED`).
pub fn generate_empty(out_dir: &Path) -> Result<(), EmbedError> {
    let src = render(&[], &out_dir.join("assets"));
    fs::write(out_dir.join("assets.rs"), src).map_err(|e| EmbedError::io("write assets.rs", e))
}

/// Render the generated `assets.rs` source (pure — testable without I/O).
fn render(entries: &[Entry], assets_dir: &Path) -> String {
    let mut w = String::with_capacity(4096);
    let _ = writeln!(
        w,
        "// AUTO-GENERATED by init_pro_vendor::embed (T0.2 B2, Q6). Do not edit.\n\
         // Regenerated by crates/init-pro/build.rs on each INIT_PRO_EMBED=1 build."
    );
    w.push_str("use init_pro_core::embed::EmbeddedAsset;\n\n");

    if entries.is_empty() {
        w.push_str("pub static SHA256_SUMS: &str = \"\";\n");
        w.push_str("pub static DATA_LINKS: &str = \"\";\n");
        w.push_str("pub fn embedded_assets() -> &'static [EmbeddedAsset] {\n    &[]\n}\n");
        return w;
    }

    // One static per unique SHA (content-addressed dedup).
    let mut seen = std::collections::HashSet::new();
    for e in entries {
        if seen.insert(e.sha256.as_str()) {
            let blob = assets_dir.join(format!("{}.zst", e.sha256));
            let _ = writeln!(
                w,
                "#[allow(non_upper_case_globals)]\nstatic Z_{}: &[u8] = include_bytes!({:?});",
                blob_ident(&e.sha256),
                blob.to_string_lossy()
            );
        }
    }
    w.push('\n');
    w.push_str("static ASSETS: [EmbeddedAsset; ");
    let _ = write!(w, "{}", entries.len());
    w.push_str("] = [\n");
    for e in entries {
        let _ = writeln!(
            w,
            "    EmbeddedAsset {{ path: {:?}, sha256: {:?}, size: {}, zstd: Z_{} }},",
            e.logical, e.sha256, e.size, blob_ident(&e.sha256)
        );
    }
    w.push_str("];\n\n");
    // .sha256sums manifest (k3s dataverify parity, B3)
    let sums: Vec<(String, String)> = entries
        .iter()
        .map(|e| (e.logical.clone(), e.sha256.clone()))
        .collect();
    let sha256_content = dataverify::render_sha256sums(&sums);
    let _ = writeln!(w, "\npub static SHA256_SUMS: &str = {:?};", sha256_content);

    // .links manifest — empty for v1 (no symlinks in the bundle; B5 may populate)
    let links_content = dataverify::render_links(&[]);
    let _ = writeln!(w, "pub static DATA_LINKS: &str = {:?};", links_content);

    w.push_str("pub fn embedded_assets() -> &'static [EmbeddedAsset] {\n    &ASSETS\n}\n");
    w
}

/// First 16 hex chars of SHA → valid Rust identifier suffix.
fn blob_ident(sha: &str) -> &str {
    &sha[..16]
}

/// Recursive directory walk (files only, sorted by caller).
fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.is_file() {
            out.push(path);
        }
    }
}

/// zstd-compress `data` at `level`.
fn zstd_compress(data: &[u8], level: i32) -> Result<Vec<u8>, EmbedError> {
    zstd::encode_all(std::io::Cursor::new(data), level)
        .map_err(|e| EmbedError::io("zstd compress", e))
}

/// Embed codegen failure.
#[derive(Debug)]
pub struct EmbedError {
    kind: EmbedErrorKind,
}

#[derive(Debug)]
enum EmbedErrorKind {
    Io { ctx: String, source: std::io::Error },
    NoVendorBin { path: PathBuf },
}

impl EmbedError {
    fn io(ctx: &str, source: std::io::Error) -> Self {
        EmbedError {
            kind: EmbedErrorKind::Io {
                ctx: ctx.to_string(),
                source,
            },
        }
    }

    fn no_vendor_bin(path: PathBuf) -> Self {
        EmbedError {
            kind: EmbedErrorKind::NoVendorBin { path },
        }
    }
}

impl std::fmt::Display for EmbedError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            EmbedErrorKind::Io { ctx, source } => write!(f, "{ctx}: {source}"),
            EmbedErrorKind::NoVendorBin { path } => write!(
                f,
                "vendor/bin/ is empty or missing ({}); run `INIT_PRO_VENDOR=1 cargo build` first",
                path.display()
            ),
        }
    }
}
impl std::error::Error for EmbedError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blob_ident_is_first_16_hex() {
        assert_eq!(
            blob_ident("bcfc299c1ab255e9d045ffaf2e324c0abaf58f599831a7c2c4a80b33f795de94"),
            "bcfc299c1ab255e9"
        );
    }

    #[test]
    fn render_empty_produces_empty_slice() {
        let src = render(&[], Path::new("/fake/assets"));
        assert!(src.contains("use init_pro_core::embed::EmbeddedAsset"));
        assert!(src.contains("&[]"));
        assert!(!src.contains("include_bytes!"));
    }

    #[test]
    fn render_emits_include_bytes_and_entries() {
        let entries = vec![
            Entry {
                logical: "bin/aux/bridge".into(),
                sha256: "aaa1111111111111aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".into(),
                size: 100,
                compressed_len: 40,
            },
            Entry {
                logical: "bin/runc".into(),
                sha256: "bbb2222222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".into(),
                size: 200,
                compressed_len: 80,
            },
        ];
        let src = render(&entries, Path::new("/fake/assets"));
        assert!(src.contains("include_bytes!(\"/fake/assets/aaa111"));
        assert!(src.contains("include_bytes!(\"/fake/assets/bbb222"));
        assert!(src.contains("path: \"bin/runc\""));
        assert!(src.contains("path: \"bin/aux/bridge\""));
        assert!(src.contains("zstd: Z_bbb2222222222222"));
        assert!(src.contains("size: 200"));
        // B3: manifests present
        assert!(src.contains("pub static SHA256_SUMS"));
        assert!(src.contains("pub static DATA_LINKS"));
        assert!(src.contains("aaa111"));
    }

    #[test]
    fn render_includes_sha256sums_manifest() {
        let entries = vec![Entry {
            logical: "bin/runc".into(),
            sha256: "bcfc299c1ab255e9d045ffaf2e324c0abaf58f599831a7c2c4a80b33f795de94".into(),
            size: 100,
            compressed_len: 40,
        }];
        let src = render(&entries, Path::new("/fake"));
        // sha256sums content must contain the hash + path in the standard format
        assert!(src.contains("bcfc299c1ab255e9d045ffaf2e324c0abaf58f599831a7c2c4a80b33f795de94  bin/runc"));
    }

    #[test]
    fn render_dedup_identical_sha() {
        let sha = "ccc3333333333333cccccccccccccccccccccccccccccccccccccccccccc";
        let entries = vec![
            Entry { logical: "bin/a".into(), sha256: sha.into(), size: 10, compressed_len: 4 },
            Entry { logical: "bin/b".into(), sha256: sha.into(), size: 10, compressed_len: 4 },
        ];
        let src = render(&entries, Path::new("/fake"));
        // Only one include_bytes! for the shared SHA.
        assert_eq!(src.matches("include_bytes!").count(), 1);
        // Both entries reference the same static.
        assert_eq!(src.matches("Z_ccc3333333333333").count(), 3); // 1 decl + 2 refs
    }

    #[test]
    fn report_summary_shows_ratio() {
        let r = EmbedReport {
            count: 2,
            total_bytes: 1000,
            compressed_bytes: 300,
            files: vec![],
        };
        assert_eq!(r.summary(), "2 files: 1000 -> 300 bytes (30%)");
    }

    #[test]
    fn report_summary_zero_division_safe() {
        let r = EmbedReport::default();
        assert_eq!(r.summary(), "0 files: 0 -> 0 bytes (0%)");
    }

    #[test]
    fn zstd_compress_round_trips() {
        let data = b"hello world ".repeat(1000);
        let compressed = zstd_compress(&data, 19).unwrap();
        assert!(compressed.len() < data.len());
        let decompressed = zstd::decode_all(std::io::Cursor::new(&compressed[..])).unwrap();
        assert_eq!(decompressed, data);
    }
}
